### ISSUE TITLE
Repository not found in jitpack

### ISSUE THREAD

**Issue by jenisonleo** [contentful/rich-text-renderer.java#1]
Getting this error **Repository not found: java.rich-text-renderer.contentful.github.com.all:master-SNAPSHOT:** for gradle compile of the library for android as mentioned [here](https://github.com/contentful/rich-text-renderer.java/blob/master/android/README.md)

**Comment by mariobodemann** [comment]
Hey,

that is odd. Can you try again, and if it still doesn't work, do you mind sharing your code with me?

Greetings, Mario.

**Comment by jenisonleo** [comment]
tried compiling in an empty project https://github.com/jenisonleo/rich-text-renderer.java-bug-report

**Comment by mariobodemann** [comment]
Hello,

and thanks so much for the sample project. This helped me a lot in finding out the problem.

The changes I need to make to find the repository where twofold:

*1. Adding a `~` in the dependency definition instead of a `.`:*

Due to the special meanings of dots in the repository resolution from jitpack (the dependency provider), you have to replace the `.` from the `.java` part with a tilde: `~`. The complete statement would then look like this:

```gradle
implementation 'com.github.contentful.rich-text-renderer~java:all:master-SNAPSHOT'
```
(I will update the documentation in a bit)

*2. Targeting min sdk 26*

Due to the fact that Android [updated its minimum requirements November 1st](https://developer.android.com/distribute/best-practices/develop/target-sdk) we took the liberty to make the new rendering library use Java 8 features and therefore an update of the _app/build.gradle_s _minSdkVersion_ might be needed like so:

```
-        minSdkVersion 21
+        minSdkVersion 26
``` 
(As in replacing the 21 with a 26)

I hope this could help you succeed with Contentful, If not, please do not hesitate to contact us again.


Greetings,
Mario

**Comment by jenisonleo** [comment]
thanks @mariobodemann .
`implementation 'com.github.contentful.rich-text-renderer~java:all:master-SNAPSHOT'`
this answer works fine. This issue can be closed once document is updated.
